-- Add welcome message fields to bots table
ALTER TABLE bots ADD COLUMN IF NOT EXISTS initial_message TEXT;
ALTER TABLE bots ADD COLUMN IF NOT EXISTS top_message TEXT;
ALTER TABLE bots ADD COLUMN IF NOT EXISTS button_message VARCHAR(255);
ALTER TABLE bots ADD COLUMN IF NOT EXISTS activate_cta BOOLEAN DEFAULT false;
ALTER TABLE bots ADD COLUMN IF NOT EXISTS media_1_url VARCHAR(500);
ALTER TABLE bots ADD COLUMN IF NOT EXISTS media_2_url VARCHAR(500);
ALTER TABLE bots ADD COLUMN IF NOT EXISTS media_3_url VARCHAR(500);

